@startuml
title Proses Bisnis Kshoe's

start
:Inisiasi Proyek;
:Menentukan Tujuan Bisnis;
:Menentukan Kriteria Keberhasilan;

:Persiapan;
:Menentukan Tim Proyek;
:Pengumpulan dan Validasi Data Awal;
:Merancang Arsitektur Teknis dan Non-Teknis;

:Pengembangan;
:Pengembangan Model Analitik;
:Pengembangan Sistem Rekomendasi;
:Integrasi Sistem dan API;
:Pengembangan Fitur E-commerce;
:Pengujian Fitur;

:Peluncuran;
:Meluncurkan Fitur Rekomendasi;
:Meluncurkan Kampanye Pemasaran;
:Memantau Kinerja Awal;

:Evaluasi dan Iterasi;
:Melakukan Evaluasi Rutin;
:Pengumpulan Umpan Balik;
:Iterasi dan Peningkatan;

:Proyek Selesai;

stop

@enduml
